// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEZ5S9eSKiZtn2dHEtBUipApyjDwry-SE',
    appId: '1:341494576055:web:c49838a6c7c0d23f09ae32',
    messagingSenderId: '341494576055',
    projectId: 'gossapp-589dd',
    authDomain: 'gossapp-589dd.firebaseapp.com',
    storageBucket: 'gossapp-589dd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7UFbG6mLJcyzRAUlwK39n-2ZDnUiRpGA',
    appId: '1:341494576055:android:833f0a82f1e1996c09ae32',
    messagingSenderId: '341494576055',
    projectId: 'gossapp-589dd',
    storageBucket: 'gossapp-589dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUFtDpLGLIWZzuR-QjCmAYzM5rAMWTybc',
    appId: '1:341494576055:ios:042bec08db3ce91b09ae32',
    messagingSenderId: '341494576055',
    projectId: 'gossapp-589dd',
    storageBucket: 'gossapp-589dd.appspot.com',
    iosClientId: '341494576055-bo0att6md3kgb2caiv0hrbsrf7tegao7.apps.googleusercontent.com',
    iosBundleId: 'com.example.gosapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUFtDpLGLIWZzuR-QjCmAYzM5rAMWTybc',
    appId: '1:341494576055:ios:042bec08db3ce91b09ae32',
    messagingSenderId: '341494576055',
    projectId: 'gossapp-589dd',
    storageBucket: 'gossapp-589dd.appspot.com',
    iosClientId: '341494576055-bo0att6md3kgb2caiv0hrbsrf7tegao7.apps.googleusercontent.com',
    iosBundleId: 'com.example.gosapp',
  );
}
